CREATE DEFINER=`oasis_dev`@`%` PROCEDURE `GetReformattedSurveys`()
BEGIN
 SELECT id, userID, dateCompleted,completed, max(case when question=1 then answers else null end) Q1,
 max(case when question = 2 and answers like 'Yes' then 1 when question = 2 and answers like 'No' then 0 when question = 2 then answers else null end) Q2,
 max(case when question = 3 then answers else null end) Q3,
 max(case when question = 4 then answers else null end) Q4,
 max(case when question = 5 then answers else null end) Q5,
	max(case when question = 5 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '(', -1) else null end) Q5_1,
	max(case when question = 5 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ')', 1) else null end) Q5_2,
 max(case when question = '6' then answers else null end) Q6,
    max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) like '1' then 1 else null end) Q6_1,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) like '1' then 1 else null end) Q6_2,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 3), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 3), ',', -1) like '1' then 1 else null end) Q6_3,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 4), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 4), ',', -1) like '1' then 1 else null end) Q6_4,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 5), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 5), ',', -1) like '1' then 1 else null end) Q6_5,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 6), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 6), ',', -1) like '1' then 1 else null end) Q6_6,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 7), ',', -1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 7), ',', -1) like '1' then 1 else null end) Q6_7,
	max(case when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) like '' then 0 when question = '6' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) like '1' then 1 else null end) Q6_8,
 max(case when question = '6_1' then answers else null end) Q6_1,
 max(case when question = '6_2' then answers else null end) Q6_2,
 max(case when question = '6_3' then answers else null end) Q6_3,
 max(case when question = '6_4' then answers else null end) Q6_4,
 max(case when question = '6_5' then answers else null end) Q6_5,
 max(case when question = '6_6' then answers else null end) Q6_6,
 max(case when question = '6_7' then answers else null end) Q6_7,
 max(case when question = '6_8' then answers else null end) Q6_8,
 max(case when question = 7 and answers like 'Yes' then 1 when question = 7 and answers like 'No' then 0 when question = 7 then answers else null end) Q7,
 max(case when question = '8' then answers else null end) Q8,
	max(case when question = '8' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) else null end) Q8_1,
	max(case when question = '8' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) else null end) Q8_2,
	max(case when question = '8' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 3), ',', -1) else null end) Q8_3,
	max(case when question = '8' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 4), ',', -1) else null end) Q8_4,
	max(case when question = '8' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) else null end) Q8_5,
 max(case when question = '8_1' then answers else null end) Q8_1,
 max(case when question = '8_2' then answers else null end) Q8_2,
 max(case when question = '8_3' then answers else null end) Q8_3,
 max(case when question = '8_4' then answers else null end) Q8_4,
 max(case when question = '8_5' then answers else null end) Q8_5,
 max(case when question = 9 then answers else null end) Q9,
 max(case when question = '10' then answers else null end) Q10,
  max(case when question = '10' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) else null end) Q10_1,
  max(case when question = '10' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) else null end) Q10_2,
  max(case when question = '10' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 3), ',', -1) else null end) Q10_3,
  max(case when question = '10' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 4), ',', -1) else null end) Q10_4,
  max(case when question = '10' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) else null end) Q10_5,
max(case when question = '10_1' then answers else null end) Q10_1, 
max(case when question = '10_2' then answers else null end) Q10_2,
max(case when question = '10_3' then answers else null end) Q10_3,
max(case when question = '10_4' then answers else null end) Q10_4,
max(case when question = '10_5' then answers else null end) Q10_5,
 max(case when question = '11' then answers else null end) Q11,
   max(case when question = '11' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) else null end) Q11_1,
  max(case when question = '11' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) else null end) Q11_2,
  max(case when question = '11' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 3), ',', -1) else null end) Q11_3,
  max(case when question = '11' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 4), ',', -1) else null end) Q11_4,
  max(case when question = '11' then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) else null end) Q11_5,
max(case when question = '11_1' then answers else null end) Q11_1, 
max(case when question = '11_2' then answers else null end) Q11_2, 
max(case when question = '11_3' then answers else null end) Q11_3, 
max(case when question = '11_4' then answers else null end) Q11_4, 
max(case when question = '11_5' then answers else null end) Q11_5,
 max(case when question = 12 then answers else null end) Q12,
 max(case when question = 13 and answers like 'Yes' then 1 when question = 13 and answers like 'No' then 0 when question = 13 then answers else null end) Q13,
 max(case when question = 14 then answers else null end) Q14,
	max(case when question = 14 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) else null end) Q14_1,
  max(case when question = 14 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) else null end) Q14_2,
	max(case when question = 14 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '(', -1) else null end) Q14_1,
  max(case when question = 14 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ')', 1) else null end) Q14_2,
 max(case when question = 15 then answers else null end) Q15,
 max(case when question = 16 then answers else null end) Q16,
 max(case when question = 16 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '(', -1) else null end) Q16_1,
	max(case when question = 16 then SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ')', 1) else null end) Q16_2,
 max(case when question = 17 then answers else null end) Q17,
 max(case when question = '18' then answers else null end) Q18,
	max(case when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) like '' then 0 when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 1), '[', -1) like '1' then 1 else null end) Q18_1,
	max(case when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) like '' then 0 when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', 2), ',', -1) like '1' then 1 else null end) Q18_2,
	max(case when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) like '' then 0 when question = '18' and SUBSTRING_INDEX(SUBSTRING_INDEX(answers, ',', -1), ']', 1) like '1' then 1 else null end) Q18_3,
max(case when question = '18_1' then answers else null end) Q18_1, 
max(case when question = '18_2' then answers else null end) Q18_2,
max(case when question = '18_3' then answers else null end) Q18_3,
 max(case when question = 19 then answers else null end) Q19,
 max(case when question = 20 then answers else null end) Q20
 FROM oasis_dev.CompletedSurveys
 group by dateCompleted;
END